package LoginIntroServlet;

import DAO.FoodDAO;
import java.io.IOException;
import java.sql.*;
import java.util.*;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.*;
import model.DatabaseConnection;

@WebServlet("/login_intro")
public class LoginIntroServlet extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        request.setCharacterEncoding("UTF-8");
        response.setCharacterEncoding("UTF-8");

        String email = request.getParameter("email");
        String password = request.getParameter("password");

        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(
                "SELECT IdUser, userName, Avatar, role FROM users WHERE Email = ? AND Password = ?")) {

            stmt.setString(1, email);
            stmt.setString(2, password);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                String idUser = rs.getString("IdUser");
                String userName = rs.getString("userName");
                String avatar = rs.getString("Avatar");
                String role = rs.getString("role");

                // Lưu thông tin vào session
                HttpSession session = request.getSession();
                session.setAttribute("user_id", idUser);
                session.setAttribute("user_email", email);
                session.setAttribute("login_success", "Đăng nhập thành công!");

                Map<String, Object> userInfo = new HashMap<>();
                userInfo.put("id", idUser);
                userInfo.put("username", userName);
                userInfo.put("avatar", avatar);
                userInfo.put("role", role);
                session.setAttribute("user", userInfo);

                // Gọi hàm tạo khuyến mãi (tùy chọn)
                AutoGenerateDiscount.generate(idUser);

                // Xử lý theo role
                if ("user".equals(role)) {
                    List<Map<String, Object>> foodPhobien = FoodDAO.getFoods("food_phobien");
                    List<Map<String, Object>> foodMoi = FoodDAO.getFoods("food_moi");

                    request.setAttribute("foods_phobien", foodPhobien);
                    request.setAttribute("foods_moi", foodMoi);
                    request.setAttribute("success", session.getAttribute("login_success"));

                    request.getRequestDispatcher("/templates/intro.jsp").forward(request, response);

                } else if ("staff".equals(role)) {
                    request.getRequestDispatcher("/templates/dashboard_staff.jsp").forward(request, response);

                } else if ("admin".equals(role)) {
                    request.getRequestDispatcher("/templates/admin.jsp").forward(request, response);

                } else {
                    request.setAttribute("error", "Vai trò không hợp lệ!");
                    request.getRequestDispatcher("/templates/login.jsp").forward(request, response);
                }

            } else {
                request.setAttribute("error", "Sai thông tin 😖😖😖");
                request.getRequestDispatcher("/templates/login.jsp").forward(request, response);
            }

        } catch (Exception e) {
            e.printStackTrace();
            request.setAttribute("error", "Lỗi hệ thống: " + e.getMessage());
            request.getRequestDispatcher("/templates/login.jsp").forward(request, response);
        }
    }
}
